### ISSUE TITLE
Restore copyright notices

### ISSUE THREAD

**Issue by orowith2os** [Athena-OS/athena-platform-center#1]
This repository is a fork of Vanilla OS' [Control Center](https://github.com/Vanilla-OS/vanilla-control-center), and is admitted in the README here. However, there is no copyright notice in ANY of the copied files mentioning this. 

This violates the GPL, and numerous other free software licenses. Keeping the copyright notice is a legal requirement.

**Comment by D3vil0p3r** [comment]
> This repository is a fork of Vanilla OS' [Control Center](https://github.com/Vanilla-OS/vanilla-control-center), and is admitted in the README here. However, there is no copyright notice in ANY of the copied files mentioning this.
> 
> This violates the GPL, and numerous other free software licenses. Keeping the copyright notice is a legal requirement.

Thank you for the issue. Yes, we started on Vanilla OS files (as mentioned on the README) and we are working on inserting the missing comments as requested.

**Comment by D3vil0p3r** [comment]
@orowith2os check now please. If good, please close the ticket. Thank you again for your tip.
